programadjango/appdjango/urls.py
from django.urls import path

from django.contrib import admin
from .views import vistaLogin, vistaRegistro, vistaInicio, vistaReconocimientos, vistaAjustes, eliminarCuenta, cambiar_contrasena, deteccion_resultado, guardar_animal_BBDD, recuperar_contrasena, cambio_contrasena, reestablecer_contrasena 
#importamos las vistas que vamos a usar en los distintos html
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', vistaLogin, name="login"),
    path('registro/', vistaRegistro, name='registro'),  
    path('inicio/', vistaInicio, name='inicio'),  
    path('reconocimiento/', vistaReconocimientos, name='reconocimientos'),
    path('ajustes/', vistaAjustes, name='ajustes'),
    path('eliminarCuenta/', eliminarCuenta, name='eliminarCuenta'),
    path('cambiarContrasena/', cambiar_contrasena, name="cambiar_contrasena"),
    path("resultado/", deteccion_resultado, name="resultado"),
    path("guardar_animal/", guardar_animal_BBDD, name="guardar_animal"),
    path("recuperar_contrasena/", recuperar_contrasena, name= 'recuperar_contrasena'),
    path("cambio_contrasena/", cambio_contrasena, name= 'cambio_contrasena'),
    path("restablecer_contrasena/", reestablecer_contrasena, name="reestablecer_contrasena")
]

programadjango/configuraciondjango/urls.py
from django.contrib import admin
from django.urls import path, include  # Importa 'include' para incluir las URLs de la app

urlpatterns = [
    path('', include('appdjango.urls')),  # Esto incluye las URLs de tu app
]

programadjango/appdjango/models.py
from django.db import models
from django.contrib.auth import get_user_model

#creamos la tabla Lugar con sus atributos correspondientes
class Lugar(models.Model):
    latitud = models.FloatField()
    longitud = models.FloatField()
    #obligamos al programa a que la tabla en la base de datos se llame "Lugar"
    class Meta:
        db_table = 'Lugar'

#creamos la tabla Animales con sus atributos correspondientes
class Animales(models.Model):
    user = get_user_model()

    usuario = models.ForeignKey(user, on_delete=models.CASCADE, related_name='animales')  # Relación many-to-one
    nombreAnimal = models.CharField(max_length=50)
    cantidad = models.IntegerField()
    lugarEncuentro = models.ForeignKey('Lugar', on_delete=models.CASCADE)  # Relación con la tabla Lugar
    fechaHora = models.DateTimeField(auto_now_add=True) 
    #obligamos al programa a que la tabla en la base de datos se llame "Animales"
    class Meta:
        db_table = 'Animales'

programadjango/appdjango/forms.py
from django import forms
from django.core.validators import RegexValidator

#creacion del formulario del login para que el usuario pueda iniciar sesion
class LoginFormulario(forms.Form):
    correo = forms.EmailField(
        label="Correo electrónico",
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Tu correo electrónico'})
    )
    contrasena = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Tu contraseña'})
    )

#creacion del formulario de registro para que el usuario pueda registrar una cuenta en la base de datos
class RegistroFormulario(forms.Form):
    nombre = forms.CharField(
        label="Nombre",
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tu nombre'})
    )
    correo = forms.EmailField(
        label="Correo electrónico",
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'ejemplo@gmail.com'})
    )
    contrasena = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Tu contraseña'}),
        validators=[RegexValidator(
            regex=r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$',
            message="La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un número."
        )]
    )
    
    def clean_contrasena(self):
        contrasena = self.cleaned_data.get('contrasena')
        return contrasena

programadjango/appdjango/views.py
import base64
import io
import re
from PIL import Image # type: ignore
from urllib import request
from django.http import JsonResponse
from django.shortcuts import render, redirect

from django.contrib.auth.hashers import check_password
from django.contrib.auth import login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from .forms import LoginFormulario, RegistroFormulario
from .models import Animales, Lugar
from django.contrib.auth.models import User
import json
from django.http import JsonResponse
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
import numpy as np
from django.contrib.auth import update_session_auth_hash
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import logout

modeloReptiles = load_model(r"C:\Users\Jose\Desktop\TFG\Django\programadjango\appdjango\modelos\modeloReptiles.keras")
clases_modelo_reptiles = ['Culebra', 'Lagarto', 'Rana', 'Tortuga']
modeloDomestico = load_model(r"C:\Users\Jose\Desktop\TFG\Django\programadjango\appdjango\modelos\modeloDomestico.keras")
clases_modelo_domesticos = ['Bisonte', 'Burro', 'Caballo', 'Cabra', 'Cerdo', 'Cisne', 'Conejo', 'Gallina', 'Gato', 'Oveja', 'Pavo', 'Perro', 'Vaca']
modeloAves = load_model(r"C:\Users\Jose\Desktop\TFG\Django\programadjango\appdjango\modelos\modeloAve.keras")
clases_modelo_aves = ['Aguila', 'Buitre', 'Cigüeña', 'Ganso', 'Grulla', 'Halcon', 'Lechuza']
modeloSalvaje = load_model(r"C:\Users\Jose\Desktop\TFG\Django\programadjango\appdjango\modelos\modeloSalvaje.keras")
clases_modelo_salvajes = ['Ardilla', 'Ciervo', 'Jabali', 'Liebre', 'Lince', 'Lobo', 'Marmota', 'Nutria', 'Oso', 'Tejon', 'Zorro']

#vista usada para el login de nuestra pagina web
def vistaLogin(request):
    if request.method == "POST":
        formulario = LoginFormulario(request.POST)
        if formulario.is_valid(): # si el formulario es valido, recogemos los datos en variables
            correo = formulario.cleaned_data['correo']
            contrasena = formulario.cleaned_data['contrasena']

            user = User.objects.filter(email=correo).first()

            if user is None or not check_password(contrasena, user.password):
                messages.error(request, "Credenciales inválidas.")
            else:
                login(request, user)  # Logeamos el usuario
                return redirect('inicio')  # Redirigir a la página de inicio

        else:
            messages.error(request, "Formulario no válido.")
    
    else:
        formulario = LoginFormulario()

    return render(request, "appdjango/login.html", {"form": formulario})

#vista para el registro de nuestra pagina web
def vistaRegistro(request):
    if request.method == "POST":
        formulario = RegistroFormulario(request.POST)
        if formulario.is_valid():
            #cogemos los datos que ha insertado el usuario a la hora de registrarse y lo guardamos en variables
            nombre = formulario.cleaned_data['nombre']
            correo = formulario.cleaned_data['correo']
            contrasena = formulario.cleaned_data['contrasena']
            
            if not re.match(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$', contrasena): #verificamos si la contraseña cumple con los requisitos
                formulario.add_error('contrasena', 'La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un número.')
                return render(request, "appdjango/registro.html", {"form": formulario})
            else:    
                if User.objects.filter(email=correo).exists(): #verificamos que el correo no esté registrado ya en la base de datos
                    formulario.add_error('correo', 'Este correo ya está registrado.')
                    return render(request, "appdjango/registro.html", {"form": formulario})
                else:
                    if User.objects.filter(username=nombre).exists(): #verificamos que el nombre no esté registrado ya en la base de datos
                        formulario.add_error('nombre', 'Este nombre ya está registrado.')
                        return render(request, "appdjango/registro.html", {"form": formulario})
                    else:
                        #si el usuario no existe, encriptamos la contraseña y creamos un nuevo usuario insertandolo en la base de datos
                        contrasena_encriptada = make_password(contrasena)
                        nuevo_usuario = User(username=nombre, email = correo, password = contrasena_encriptada)
                        nuevo_usuario.save()
                        #una vez insertado, mandamos al usuario a logearse
                        return redirect('login')
            
    else: 
        formulario = RegistroFormulario()
    return render(request, "appdjango/registro.html", {"form": formulario})

#vista para la pagina de inicio (despues del login)
def vistaInicio(request):
    return render(request, 'appdjango/inicio.html')


 #vista para el historial de reconocimientos de animales
def vistaReconocimientos(request):
    user = request.user

    # Obtener todos los animales almacenados en la base de datos 
    animales = Animales.objects.filter(usuario = user)

    return render(request, 'appdjango/reconocimiento.html', {'animales': animales})

#vista para los ajustes de la pagina web
def vistaAjustes(request):
    return render(request, 'appdjango/ajustes.html', {'usuario': request.user, 'email': request.user.email, 'contrasena': request.user.password} )

#funcion para eliminar la cuenta del usuario que ha iniciado sesion
def eliminarCuenta(request): 
    if request.user.is_authenticated:  # Verifica si el usuario está autenticado
        user = request.user
        user.delete()  # Elimina el usuario de la base de datos
        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "error", "message": "No estás autenticado"})
    
#funcion para cambiar la contraseña del usuario que ha iniciado sesion
def cambiar_contrasena(request):
    if request.method == "POST":
        data = json.loads(request.body)
        actual = data.get("actual") #obtenemos el valor de la contraseña actual y la nueva
        nueva = data.get("nueva")

        usuario = request.user
        if not usuario.check_password(actual): #comprobamos que la contraseña actual sea correcta
            return JsonResponse({"success": False, "error": "La contraseña actual es incorrecta"}, status=400)

        usuario.set_password(nueva) #introducimos la contraseña nueva al usuario
        usuario.save() # guardamos los cambios
        update_session_auth_hash(request, usuario)  # Evita que el usuario cierre sesión

        return JsonResponse({"success": True})

    return JsonResponse({"success": False, "error": "Método no permitido"}, status=405)

def deteccion_resultado(request):
    if request.method == 'POST':
        if 'archivo' in request.FILES:
            imagen = Image.open(request.FILES['archivo'])
        elif request.POST.get('fotobase64'):
            base64_str = request.POST.get('fotobase64').split(',')[1]
            image_data = base64.b64decode(base64_str)
            imagen = Image.open(io.BytesIO(image_data))
        else:
            return render(request, 'appdjango/resultado.html', {'error':'No se recibió ninguna imagen'})

        # Preprocesamiento
        imagen = imagen.resize((128, 128))
        imagen_array = img_to_array(imagen) / 128.0
        imagen_array = np.expand_dims(imagen_array, axis=0)

        # Evaluar modelo de reptiles
        pred_reptil = modeloReptiles.predict(imagen_array)
        prob_reptil = np.max(pred_reptil)
        clase_reptil = clases_modelo_reptiles[np.argmax(pred_reptil)]

        if prob_reptil >= 0.6:
            return render(request, 'appdjango/resultado.html', {
                'clase': clase_reptil,
                'probabilidad': round(prob_reptil * 100, 2)
            })

        # Evaluar modelo doméstico
        pred_domestico = modeloDomestico.predict(imagen_array)
        prob_domestico = np.max(pred_domestico)
        clase_domestico = clases_modelo_domesticos[np.argmax(pred_domestico)]

        if prob_domestico >= 0.6:
            return render(request, 'appdjango/resultado.html', {
                'clase': clase_domestico,
                'probabilidad': round(prob_domestico * 100, 2)
            })

        # Evaluar modelo aves
        pred_aves = modeloAves.predict(imagen_array)
        prob_aves = np.max(pred_aves)
        clase_ave = clases_modelo_aves[np.argmax(pred_aves)]

        if prob_aves >= 0.6:
            return render(request, 'appdjango/resultado.html', {
                'clase': clase_ave,
                'probabilidad': round(prob_aves * 100, 2)
            })

       # Evaluar modelo salvajes
        pred_salvajes = modeloSalvaje.predict(imagen_array)
        prob_salvaje = np.max(pred_salvajes)
        clase_salvaje = clases_modelo_salvajes[np.argmax(pred_salvajes)]

        if prob_salvaje >= 0.6:
            return render(request, 'appdjango/resultado.html', {
                'clase': clase_salvaje,
                'probabilidad': round(prob_salvaje * 100, 2)
            })
            
    return render(request, 'appdjango/resultado.html', {'error': 'Método no válido'})

def obtener_coordenadas_exif(archivo_imagen):
    # Abrir la imagen para leer los datos EXIF
    imagen = Image.open(archivo_imagen)
    # Cogemos los metadatos EXIF
    exif_data = imagen._getexif()
    # Si existen metadatos EXIF
    if exif_data:
        # Obtenemos la coordenada GPS
        for tag, value in exif_data.items():
            # Encontrar la latitud y longitud en los metadatos EXIF (corresponde con la etiqueta 34853)
            if tag == 34853:  
                lat = value[2][0] / value[2][1]  # Grados latitud (2)

programadjango/appdjango/templates/appdjango/ajustes.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reconocimiento de Animales</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            text-align: center;
            background-image: url("{% static 'img/bosque1.jpg' %}");
            background-size: cover;
            background-position: center;
            position: relative;
        }

        /* Capa de oscurecimiento sobre la imagen de fondo */
        body::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.4);
            z-index: -1;
        }

        /* Estilo del contenedor de configuración */
        .settings-container {
            margin: 50px auto;
            padding: 20px;
            background: white;
            max-width: 600px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            z-index: 1;
        }
    </style>
</head>
<body>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <header>
        <h1 class="titulo">WildDetect</h1>
        <div class="menu-hamburguesa" id="hamburger-menu">
            <div></div>
            <div></div>
            <div></div>
        </div>
        <!-- Menú de navegación -->
        <ul class="nav-menu" id="nav-menu">
            <li><a href="{% url 'inicio' %}">Inicio</a></li> 
            <li><a href="{% url 'reconocimientos' %}">Últimos reconocimientos</a></li>
            <li><a href="#">Ajustes</a></li>
            <li><a href="#" onclick="mostrarMensajeCerrarSesion()"><strong>Cerrar Sesión</a></li>
        </ul>
    </header>

    <div class="settings-container">
        <h1>Configuración de la cuenta</h1>
        <br>
        <img src="{% static 'img/cuenta.png' %}" alt="Imagen de la cuenta" width="180">
        <br>
        <h3>Bienvenido {{ usuario }}</h3>
        <h5>Correo: {{email}}</h5>
        <br> 
        <button onclick="mostrarMensajeCambiarContrasena()">Cambiar Contraseña</button>
        <br>
        <button onclick="mostrarMensajeEliminarCuenta()">Eliminar Cuenta</button>
        <br>
    </div>

    <div id="cerrarSesion" class="modal">
        <div class="modal-content">
            <p>¿Estás seguro de que quieres cerrar sesión?</p>
            <button onclick="cerrarSesion()">Sí</button>
            <button onclick="ocultarMensaje()">No</button>
        </div>
    </div>

    <div id="eliminarCuenta" class="modal">
        <div class="modal-content">
            <h3 style="color: red">¿Estás seguro de que quieres eliminar la cuenta?</h3>
            <p>Se perderá toda la información</p>
            <button onclick="eliminarCuenta1()">Sí</button>
            <button onclick="ocultarMensajeEliminarCuenta()">No</button>
        </div>
    </div>

    <div id="cambiarContrasena" class="modal" style="display: none;">
        <div class="modal-content">
            <h2>Cambiar Contraseña</h2>
            <form id="formCambiarContrasena" onsubmit="cambiarContrasena(event)">
                {% csrf_token %}
                <label for="actual">Contraseña Actual:</label>
                <input type="password" id="actual" name="actual" required>
                <br><br>
                <label for="nueva">Nueva Contraseña:</label>
                <input type="password" id="nueva" name="nueva" required>
                <br><br>
                <label for="confirmar">Confirmar Nueva Contraseña:</label>
                <input type="password" id="confirmar" name="confirmar" required>
                <br><br>
                <button type="submit">Guardar Cambios</button>
                <button type="button" onclick="cancelarContrasena()">Cancelar</button>
            </form>
        </div>
    </div>


    <script>
        document.getElementById("hamburger-menu").addEventListener("click", function() {
            const navMenu = document.getElementById("nav-menu");
            navMenu.classList.toggle("active");
        });

        function mostrarMensajeCerrarSesion() {
            document.getElementById("cerrarSesion").style.display = "block";
        }

        function cerrarSesion() {
            window.location.href = "/"; 
        }

        function ocultarMensaje() {
            document.getElementById("cerrarSesion").style.display = "none";
        }

        function mostrarMensajeCambiarContrasena() {
            document.getElementById("cambiarContrasena").style.display = "flex";
        }

        function cancelarContrasena() {
            document.getElementById("cambiarContrasena").style.display = "none";
        }

        function cambiarContrasena(event) {
            event.preventDefault();
            
            let actual = document.getElementById("actual").value;
            let nueva = document.getElementById("nueva").value;
            let confirmar = document.getElementById("confirmar").value;

            // Validación de campos vacíos
            if (!actual || !nueva || !confirmar) {
                alert("Todos los campos son obligatorios");
                return;
            }

            // Validación de contraseñas coincidentes
            if (nueva !== confirmar) {
                alert("Las contraseñas no coinciden");
                return;
            }

            // Validación de la contraseña nueva (mínimo 8 caracteres, una mayúscula, una minúscula y un número)
            const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/;
            if (!passwordRegex.test(nueva)) {
                alert("La nueva contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un número.");
                return;
            }

            // Enviar la solicitud para cambiar la contraseña
            fetch("{% url 'cambiar_contrasena' %}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": document.querySelector("[name=csrfmiddlewaretoken]").value
                },
                body: JSON.stringify({
                    actual: actual,
                    nueva: nueva
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert("Contraseña cambiada con éxito");
                    document.getElementById("cambiarContrasena").style.display = "none";
                    document.getElementById("formCambiarContrasena").reset();
                } else {
                    alert("Error: " + data.error);
                }
            })
            .catch(error => console.error("Error:", error));
        }


        function mostrarMensajeEliminarCuenta() {
            document.getElementById("eliminarCuenta").style.display = "block";
        }

        function eliminarCuenta1() {
            const csrfToken = document.querySelector('[name="csrfmiddlewaretoken"]').value;
            if (!csrfToken) {
                console.error("No se encontró el token CSRF");
                return;
            }

            fetch(`/eliminarCuenta/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': csrfToken,
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    window.location.href = "/";
                } else {
                    alert(data.message);
                }
            })
            .catch(error => {
                console.error('Error: ', error);
                alert("Hay un error al eliminar la cuenta");
            });
        }

        function ocultarMensajeEliminarCuenta() {
            document.getElementById("eliminarCuenta").style.display = "none";
        }
    </script>
</body>
</html>

programadjango/appdjango/templates/appdjango/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
    {% load static %}
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-image: url("{% static 'img/bosque.jpg' %}");
            background-size: cover;
            background-position: center;
            position: relative;
        }

        body::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.4);
            z-index: -1;
        }

        /* Contenedor blanco */
        .container {
            background-color: #ffffff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 400px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 15px;
            position: relative;
        }

        label {
            font-size: 14px;
            color: #333;
            margin-bottom: 5px;
            display: block;
        }

        input {
            width: 100%;
            padding: 10px;
            font-size: 14px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-sizing: border-box;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: rgb(9, 136, 13);
            color: white;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px;
        }

        button:hover {
            background-color: rgb(1, 107, 5);
        }

        .registrar_link {
            text-align: center;
            margin-top: 15px;
        }

        .registrar_link p {
            font-size: 14px;
        }

        .registrar_link a {
            color: rgb(9, 136, 13);
            text-decoration: none;
        }

        .registrar_link a:hover {
            text-decoration: underline;
        }

        /* Estilo para las alertas */
        .alert {
            padding: 15px;
            margin: 10px 0;
            border-radius: 5px;
            font-size: 16px;
            text-align: center;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .alert-error {
            color: rgb(196, 16, 34);
        }

        /* Estilo para el icono del ojo */
        #eye-icon {
            position: absolute;
            right: 10px;
            top: 50%;
            transform: translateY(-50%);
            cursor: pointer;
        }

        /* Responsive */
        @media (max-width: 600px) {
            body {
                padding: 10px;
            }

            .container {
                padding: 20px;
                max-width: 100%;
                width: 90%;
            }

            h2 {
                font-size: 18px;
            }

            label {
                font-size: 12px;
            }

            input {
                font-size: 12px;
                padding: 8px;
            }

            button {
                font-size: 14px;
                padding: 12px;
            }

            .registrar_link p {
                font-size: 12px;
            }

            .alert {
                font-size: 14px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>INICIAR SESIÓN</h2>
        {% if form.errors %}
            <div class="alert alert-error">
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}

        {% if messages %}
            <div class="alert">
                {% for message in messages %}
                    <div class="alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="form-group">
                {{ form.correo.label_tag }}
                {{ form.correo }}
            </div>

            <div class="form-group">
                {{ form.contrasena.label_tag }}
                <div style="position: relative;">
                    {{ form.contrasena }}
                    <span id="eye-icon">&#128065;</span>
                </div>
            </div>

            <button type="submit">Iniciar Sesión</button>
        </form>

        <!-- Enlace para recuperar contraseña -->
        <div class="registrar_link">
            <p><a href="#" id="forgot-password-link">¿Olvidaste tu contraseña?</a></p>
        </div>

        <!-- Contenedor oculto para recuperar contraseña -->
        <div id="forgot-password-container" style="display: none; margin-top: 20px;">
            <h3 style="text-align: center;">Recuperar contraseña</h3>
            <form method="POST" action="{% url 'recuperar_contrasena' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email_recuperacion">Correo electrónico</label>
                    <input type="email" id="email_recuperacion" name="email_recuperacion" required>
                </div>
                <button type="submit" id="btn_enviarenlace" name="btn_enviarenlace">Enviar enlace</button>
            </form>
        </div>

        <div class="registrar_link">
            <p>¿No tienes cuenta? <a href="{% url 'registro' %}">Regístrate</a></p>
        </div>
    </div>


    <script>
        const passwordInput = document.querySelector('#id_contrasena');
        const eyeIcon = document.getElementById('eye-icon');

        eyeIcon.addEventListener('click', function() {
            if (passwordInput.type === 'password') {
                passwordInput.type = 'text';
                eyeIcon.innerHTML = '&#128065;&#10060;';
            } else {
                passwordInput.type = 'password';
                eyeIcon.innerHTML = '&#128065;';
            }
        });

        const olvidarContraseñaLink = document.getElementById('forgot-password-link');
        const olvidarContraseñaContenedor = document.getElementById('forgot-password-container');

        olvidarContraseñaLink.addEventListener('click', function(event) {
            event.preventDefault();
            olvidarContraseñaContenedor.style.display = 
                olvidarContraseñaContenedor.style.display === 'none' ? 'block' : 'none';
        });

    </script>
</body>
</html>